name: kapi

services:
  eia-carob:
    container_name: eia-carob-data
    image: iita/eia-carob:0.1.0
    build:
      context: .
      dockerfile: Dockerfile-eia-carob
    volumes:
      - ${RAW_DATA}:/usr/local/data/carob-eia # input raw data
      - ${COMPILED_DATA}:/usr/local/data/eia-carob/data # output carob-processed data (used by kapi)
    command: ["Rscript", "compile.R"]
  kapi:
    container_name: kapi
    image: iita/kapi:0.0.1
    build: 
      context: .
      dockerfile: Dockerfile-kapi
    restart: always
    ports:
      - "8080:8567"
    volumes:
      - ./logs:/var/www/kapi/app/logs
      - ./secrets:/var/www/kapi/app/secrets
      - ${COMPILED_DATA}:/var/www/kapi/eia-carob/data # mounts the compiled eia-carob directory to the target in kapi

networks:
  default:
    name: kapi
